/* Generated from the entries marked `good` in:
 * https://huggingface.co/datasets/malcolmrey/various/blob/main/h3-center/known-characters/INDEX.md
 *
 * Keep this as compact source data. The picker derives ids, short prompts,
 * and semantic subcategories in reference-presets.ts.
 */

export const KNOWN_CHARACTERS = [
  ["Abby Sciuto","Pauley Perrette","NCIS"],
  ["Ace Ventura","Jim Carrey","Ace Ventura"],
  ["Achilles","Brad Pitt","Troy"],
  ["Adam Driver","Adam Driver","Real Person / Celebrity"],
  ["Adam Maitland","Alec Baldwin","Beetlejuice"],
  ["Adam Sandler","Adam Sandler","Real Person / Celebrity"],
  ["Adonis Creed","Michael B. Jordan","Creed"],
  ["Adrian Monk","Tony Shalhoub","Monk"],
  ["Agent J","Will Smith","Men in Black"],
  ["Aishwarya Rai","Aishwarya Rai","Real Person / Celebrity"],
  ["Alan Dutch Schaefer","Arnold Schwarzenegger","Predator"],
  ["Alan Harper","Jon Cryer","Two and a Half Men"],
  ["Alan Turing","Benedict Cumberbatch","The Imitation Game"],
  ["Aldo Raine","Brad Pitt","Inglourious Basterds"],
  ["Alec Baldwin","Alec Baldwin","Real Person / Celebrity"],
  ["Alex Munday","Lucy Liu","Charlie's Angels"],
  ["Alfred Borden","Christian Bale","The Prestige"],
  ["Alluri Sitarama Raju","Ram Charan","RRR"],
  ["Alonzo Harris","Denzel Washington","Training Day"],
  ["Alvy Singer","Woody Allen","Annie Hall"],
  ["Amy Farrah Fowler","Mayim Bialik","The Big Bang Theory"],
  ["Anakin Skywalker","Hayden Christensen","Star Wars"],
  ["Andrew Garfield","Andrew Garfield","Real Person / Celebrity"],
  ["Andy Bernard","Ed Helms","The Office"],
  ["Andy Lau","Andy Lau","Real Person / Celebrity"],
  ["Andy Sachs","Anne Hathaway","The Devil Wears Prada"],
  ["Andy Stitzer","Steve Carell","The 40-Year-Old Virgin"],
  ["Angel","David Boreanaz","Buffy the Vampire Slayer"],
  ["Angelina Jolie","Angelina Jolie","Real Person / Celebrity"],
  ["Annalise Keating","Viola Davis","How to Get Away with Murder"],
  ["Anne Hathaway","Anne Hathaway","Real Person / Celebrity"],
  ["Annette Hargrove","Reese Witherspoon","Cruel Intentions"],
  ["Anthony DiNozzo","Michael Weatherly","NCIS"],
  ["Anthony Hopkins","Anthony Hopkins","Real Person / Celebrity"],
  ["Anthony Mackie","Anthony Mackie","Real Person / Celebrity"],
  ["Ashton Kutcher","Ashton Kutcher","Real Person / Celebrity"],
  ["Axel Foley","Eddie Murphy","Beverly Hills Cop"],
  ["Barack Obama","Barack Obama","Real Person / Celebrity"],
  ["Barney Ross","Sylvester Stallone","The Expendables"],
  ["Barney Stinson","Neil Patrick Harris","How I Met Your Mother"],
  ["Barry Allen / The Flash","Grant Gustin","The Flash"],
  ["Bella Swan","Kristen Stewart","Twilight"],
  ["Ben Affleck","Ben Affleck","Real Person / Celebrity"],
  ["Ben Stiller","Ben Stiller","Real Person / Celebrity"],
  ["Benjamin Franklin Gates","Nicolas Cage","National Treasure"],
  ["Benoit Blanc","Daniel Craig","Knives Out"],
  ["Bernadette Rostenkowski","Melissa Rauch","The Big Bang Theory"],
  ["Bertie Wooster","Hugh Laurie","Jeeves and Wooster"],
  ["Beth Smith","Sarah Chalke","Rick and Morty"],
  ["Beyonce","Beyonce","Real Person / Celebrity"],
  ["Big Bird","Big Bird","Sesame Street"],
  ["Bilbo Baggins","Martin Freeman","The Hobbit"],
  ["Billy Butcher","Karl Urban","The Boys"],
  ["Billy Costigan","Leonardo DiCaprio","The Departed"],
  ["Bjorn Ironside","Alexander Ludwig","Vikings"],
  ["Black Widow","Scarlett Johansson","Marvel's Avengers"],
  ["Blake","Alec Baldwin","Glengarry Glen Ross"],
  ["Bobby Singer","Jim Beaver","Supernatural"],
  ["Brad Pitt","Brad Pitt","Real Person / Celebrity"],
  ["Brennan Huff","Will Ferrell","Step Brothers"],
  ["Brick Tamland","Steve Carell","Anchorman"],
  ["Bruce Banner","Mark Ruffalo","Marvel's Avengers"],
  ["Bruce Wayne","Christian Bale","The Dark Knight"],
  ["Bruce Wayne / Batman","Ben Affleck","Batman v Superman"],
  ["Bruce Wayne / Batman","Christian Bale","The Dark Knight"],
  ["Bruce Wayne / Batman","George Clooney","Batman & Robin"],
  ["Bruce Wayne / Batman","Robert Pattinson","The Batman"],
  ["Bryan Mills","Liam Neeson","Taken"],
  ["Buddy","Will Ferrell","Elf"],
  ["Buffy Summers","Sarah Michelle Gellar","Buffy the Vampire Slayer"],
  ["Calvin Candie","Leonardo DiCaprio","Django Unchained"],
  ["Cameron Poe","Nicolas Cage","Con Air"],
  ["Captain Ellerby","Alec Baldwin","The Departed"],
  ["Captain Jack Sparrow","Johnny Depp","Pirates of the Caribbean"],
  ["Captain John Miller","Tom Hanks","Saving Private Ryan"],
  ["Captain Raymond Holt","Andre Braugher","Brooklyn Nine-Nine"],
  ["Caroline Channing","Beth Behrs","2 Broke Girls"],
  ["Carrie Bradshaw","Sarah Jessica Parker","Sex and the City"],
  ["Carrie Mathison","Claire Danes","Homeland"],
  ["Castiel","Misha Collins","Supernatural"],
  ["Castor Troy","John Travolta","Face/Off"],
  ["Castor Troy","Nicolas Cage","Face/Off"],
  ["Catwoman / Selina Kyle","Michelle Pfeiffer","Batman Returns"],
  ["Celeste Wright","Nicole Kidman","Big Little Lies"],
  ["Chan Wing-yan","Tony Leung Chiu-wai","Infernal Affairs"],
  ["Chandler Bing","Matthew Perry","Friends"],
  ["Charlie Harper","Charlie Sheen","Two and a Half Men"],
  ["Chef Gordon Ramsay","Gordon Ramsay","Hell's Kitchen"],
  ["Chev Chelios","Jason Statham","Crank"],
  ["Chloe Decker","Lauren German","Lucifer"],
  ["Chon Wang","Jackie Chan","Shanghai Noon"],
  ["Chow Mo-wan","Tony Leung Chiu-wai","In the Mood for Love"],
  ["Chuck Bartowski","Zachary Levi","Chuck"],
  ["Chuck Noland","Tom Hanks","Cast Away"],
  ["Clara Oswald","Jenna Coleman","Doctor Who"],
  ["Clark Kent","Tom Welling","Smallville"],
  ["Cliff Booth","Brad Pitt","Once Upon a Time in Hollywood"],
  ["Clint Barton / Hawkeye","Jeremy Renner","Marvel's Avengers"],
  ["Colin Farrell","Colin Farrell","Real Person / Celebrity"],
  ["Commodus","Joaquin Phoenix","Gladiator"],
  ["Conan","Arnold Schwarzenegger","Conan the Barbarian"],
  ["Conan O'Brien","Conan O'Brien","Late Night"],
  ["Cristiano Ronaldo","Cristiano Ronaldo","Real Person / Celebrity"],
  ["Daemon Targaryen","Matt Smith","House of the Dragon"],
  ["Daenerys Targaryen","Emilia Clarke","Game of Thrones"],
  ["Dana Scully","Gillian Anderson","The X-Files"],
  ["Daniel Craig","Daniel Craig","Real Person / Celebrity"],
  ["Daniel Hillard / Mrs. Doubtfire","Robin Williams","Mrs. Doubtfire"],
  ["Danny Ocean","George Clooney","Ocean's Eleven"],
  ["Darlene Alderson","Carly Chaikin","Mr. Robot"],
  ["Darth Vader (voiced by James Earl Jones)","Darth Vader (voiced by James Earl Jones)","Star Wars"],
  ["Daryl Dixon","Norman Reedus","The Walking Dead"],
  ["Data","Brent Spiner","Star Trek: The Next Generation"],
  ["Dave Chappelle","Dave Chappelle","Chappelle's Show"],
  ["David Attenborough","David Attenborough","Real Person / Celebrity"],
  ["David Letterman","David Letterman","Late Show"],
  ["Deadpool","Ryan Reynolds","Deadpool / Marvel's Avengers"],
  ["Dean Winchester","Jensen Ackles","Supernatural"],
  ["Deckard Shaw","Jason Statham","Fast & Furious"],
  ["Denzel Washington","Denzel Washington","Real Person / Celebrity"],
  ["Derek Zoolander","Ben Stiller","Zoolander"],
  ["Detective David Mills","Brad Pitt","Se7en"],
  ["Detective Rosa Diaz","Stephanie Beatriz","Brooklyn Nine-Nine"],
  ["Dexter Morgan","Michael C. Hall","Dexter"],
  ["Diana Prince / Wonder Woman","Gal Gadot","Wonder Woman"],
  ["Django","Jamie Foxx","Django Unchained"],
  ["Django Freeman","Jamie Foxx","Django Unchained"],
  ["Doctor Stephen Strange","Benedict Cumberbatch","Doctor Strange"],
  ["Doctor Strange","Benedict Cumberbatch","Marvel's Avengers"],
  ["Dom Cobb","Leonardo DiCaprio","Inception"],
  ["Dominic Toretto","Vin Diesel","Fast & Furious"],
  ["Don Draper","Jon Hamm","Mad Men"],
  ["Donald Trump","Donald Trump","The Apprentice"],
  ["Donnie Brasco","Johnny Depp","Donnie Brasco"],
  ["Douglas Quaid","Arnold Schwarzenegger","Total Recall"],
  ["Dr. Doug Ross","George Clooney","ER"],
  ["Dr. Gregory House","Hugh Laurie","House M.D."],
  ["Dr. Hannibal Lecter","Anthony Hopkins","The Silence of the Lambs"],
  ["Dr. Hannibal Lecter","Mads Mikkelsen","Hannibal"],
  ["Dr. Jed Hill","Alec Baldwin","Malice"],
  ["Dr. John Watson","Martin Freeman","Sherlock (BBC)"],
  ["Dr. Robert Ford","Anthony Hopkins","Westworld"],
  ["Dr. Rodney McKay","David Hewlett","Stargate Atlantis"],
  ["Dr. Smolder Bravestone","Dwayne Johnson","Jumanji: Welcome to the Jungle"],
  ["Dr. Temperance Brennan","Emily Deschanel","Bones"],
  ["Dr. Walter Bishop","John Noble","Fringe"],
  ["Driver","Ryan Gosling","Drive"],
  ["Dwight Schrute","Rainn Wilson","The Office"],
  ["Dylan Sanders","Drew Barrymore","Charlie's Angels"],
  ["Eddie Brock","Tom Hardy","Venom"],
  ["Edward Cullen","Robert Pattinson","Twilight"],
  ["Edward Lewis","Richard Gere","Pretty Woman"],
  ["Edward Nygma / The Riddler","Jim Carrey","Batman Forever"],
  ["Edward Scissorhands","Johnny Depp","Edward Scissorhands"],
  ["Elaine Benes","Julia Louis-Dreyfus","Seinfeld"],
  ["Eleven","Millie Bobby Brown","Stranger Things"],
  ["Elizabeth Swann","Keira Knightley","Pirates of the Caribbean"],
  ["Elliot Alderson","Rami Malek","Mr. Robot"],
  ["Ellis Boyd 'Red' Redding","Morgan Freeman","The Shawshank Redemption"],
  ["Enola Holmes","Millie Bobby Brown","Enola Holmes"],
  ["Eric Cartman","Trey Parker","South Park"],
  ["Erik Killmonger","Michael B. Jordan","Black Panther"],
  ["Ethan Hunt","Tom Cruise","Mission: Impossible"],
  ["Eve Polastri","Sandra Oh","Killing Eve"],
  ["Fletcher Reede","Jim Carrey","Liar Liar"],
  ["Forest Whitaker","Forest Whitaker","Real Person / Celebrity"],
  ["Forrest Gump","Tom Hanks","Forrest Gump"],
  ["Fox Mulder","David Duchovny","The X-Files"],
  ["Frank Abagnale Jr.","Leonardo DiCaprio","Catch Me If You Can"],
  ["Frank Costello","Jack Nicholson","The Departed"],
  ["Frank Lucas","Denzel Washington","American Gangster"],
  ["Frank Martin","Jason Statham","The Transporter"],
  ["Frank Slade","Al Pacino","Scent of a Woman"],
  ["Frank Underwood","Kevin Spacey","House of Cards"],
  ["Gandalf","Ian McKellen","Lord of the Rings"],
  ["Gaylord Focker","Ben Stiller","Meet the Parents"],
  ["Gellert Grindelwald","Mads Mikkelsen","Fantastic Beasts"],
  ["Geordi La Forge","LeVar Burton","Star Trek: The Next Generation"],
  ["George Costanza","Jason Alexander","Seinfeld"],
  ["Glenn Rhee","Steven Yeun","The Walking Dead"],
  ["Gloria Pritchett","Sofia Vergara","Modern Family"],
  ["God","Morgan Freeman","Bruce Almighty"],
  ["Goofy","Goofy","Disney"],
  ["Gordon Gekko","Michael Douglas","Wall Street"],
  ["Gordon Ramsay","Gordon Ramsay","Real Person / Celebrity"],
  ["Gracie Hart","Sandra Bullock","Miss Congeniality"],
  ["Grant Gustin","Grant Gustin","Real Person / Celebrity"],
  ["Guy","Ryan Reynolds","Free Guy"],
  ["Hal Wilkerson","Bryan Cranston, 2000s Malcolm in the Middle era","Malcolm in the Middle"],
  ["Han Solo","Harrison Ford","Star Wars"],
  ["Hank Moody","David Duchovny","Californication"],
  ["Hansel","Owen Wilson","Zoolander"],
  ["Happy Gilmore","Adam Sandler","Happy Gilmore"],
  ["Harold Finch","Michael Emerson","Person of Interest"],
  ["Harrison Ford","Harrison Ford","Real Person / Celebrity"],
  ["Harry Callahan","Clint Eastwood","Dirty Harry"],
  ["Harry Potter","Daniel Radcliffe","Harry Potter"],
  ["Harry Tasker","Arnold Schwarzenegger","True Lies"],
  ["Heimdall","Idris Elba","Thor"],
  ["Hellboy","David Harbour","Hellboy"],
  ["Hermione Granger","Emma Watson","Harry Potter"],
  ["Homelander","Antony Starr","The Boys"],
  ["Host Neil deGrasse Tyson","Neil deGrasse Tyson","Cosmos"],
  ["Howard Ratner","Adam Sandler","Uncut Gems"],
  ["Howard Wolowitz","Simon Helberg","The Big Bang Theory"],
  ["Hugh Jackman","Hugh Jackman","Real Person / Celebrity"],
  ["Hutch Mansell","Bob Odenkirk","Nobody"],
  ["Idi Amin","Forest Whitaker","The Last King of Scotland"],
  ["Idris Elba","Idris Elba","Real Person / Celebrity"],
  ["Indiana Jones","Harrison Ford","Indiana Jones"],
  ["Inspector Lee","Jackie Chan","Rush Hour"],
  ["Iris West","Candice Patton","The Flash"],
  ["J Robert Oppenheimer","Cillian Murphy","Oppenheimer"],
  ["J.K. Simmons","J.K. Simmons","Real Person / Celebrity"],
  ["Jack Bauer","Kiefer Sutherland","24"],
  ["Jack Black","Jack Black","Real Person / Celebrity"],
  ["Jack Byrnes","Robert De Niro","Meet the Parents"],
  ["Jack Dawson","Leonardo DiCaprio","Titanic"],
  ["Jack Donaghy","Alec Baldwin","30 Rock"],
  ["Jack Nicholson","Jack Nicholson","Real Person / Celebrity"],
  ["Jack Ryan","Alec Baldwin","The Hunt for Red October"],
  ["Jack Ryan","John Krasinski","Tom Clancy's Jack Ryan"],
  ["Jack Shephard","Matthew Fox","Lost"],
  ["Jack Traven","Keanu Reeves","Speed"],
  ["Jackie Chan","Jackie Chan","Real Person / Celebrity"],
  ["Jake Gyllenhaal","Jake Gyllenhaal","Real Person / Celebrity"],
  ["Jake Peralta","Andy Samberg","Brooklyn Nine-Nine"],
  ["Jake Sully","Sam Worthington","Avatar"],
  ["James Bond","Daniel Craig","Casino Royale"],
  ["James Bond (Daniel Craig)","Daniel Craig","James Bond"],
  ["James Hunt","Chris Hemsworth","Rush"],
  ["Jamie Foxx","Jamie Foxx","Real Person / Celebrity"],
  ["Jane Smith","Angelina Jolie","Mr. & Mrs. Smith"],
  ["Jason Bourne","Matt Damon","Bourne Franchise / The Bourne Identity"],
  ["Javier Peña","Pedro Pascal","Narcos"],
  ["Jax Teller","Charlie Hunnam","Sons of Anarchy"],
  ["Jean-Luc Picard","Patrick Stewart","Star Trek: The Next Generation"],
  ["Jeff Goldblum","Jeff Goldblum","Real Person / Celebrity"],
  ["Jennifer Love Hewitt","Jennifer Love Hewitt","Real Person / Celebrity"],
  ["Jeremy Grey","Vince Vaughn","Wedding Crashers"],
  ["Jeremy Renner","Jeremy Renner","Real Person / Celebrity"],
  ["Jerry Maguire","Tom Cruise","Jerry Maguire"],
  ["Jerry Seinfeld","Jerry Seinfeld","Seinfeld"],
  ["Jesse Eisenberg","Jesse Eisenberg","Real Person / Celebrity"],
  ["Jesse Pinkman","Aaron Paul","Breaking Bad"],
  ["Jessica Chastain","Jessica Chastain","Real Person / Celebrity"],
  ["Jessica Jones","Krysten Ritter","Jessica Jones"],
  ["Jim","Cillian Murphy","28 Days Later"],
  ["Jim Carrey","Jim Carrey","Real Person / Celebrity"],
  ["Jim Halpert","John Krasinski","The Office"],
  ["Jim Hopper","David Harbour","Stranger Things"],
  ["Jimmy Conway","Robert De Niro","Goodfellas"],
  ["Jimmy Fallon","Jimmy Fallon","Real Person / Celebrity"],
  ["Joe Rogan","Joe Rogan","The Joe Rogan Experience"],
  ["Joel Miller","Pedro Pascal","The Last of Us"],
  ["Joey Tribbiani","Matt LeBlanc","Friends"],
  ["John Cena","John Cena","Real Person / Celebrity"],
  ["John Constantine","Keanu Reeves","Constantine"],
  ["John Dutton","Kevin Costner","Yellowstone"],
  ["John Locke","Terry O'Quinn","Lost"],
  ["John Luther","Idris Elba","Luther"],
  ["John Matrix","Arnold Schwarzenegger","Commando"],
  ["John McClane","Bruce Willis","Die Hard"],
  ["John Nash","Russell Crowe","A Beautiful Mind"],
  ["John Nolan","Nathan Fillion","The Rookie"],
  ["John Oliver","John Oliver","Last Week Tonight"],
  ["John Rambo","Sylvester Stallone","Rambo"],
  ["John Reese","Jim Caviezel","Person of Interest"],
  ["John Smith","Brad Pitt","Mr. & Mrs. Smith"],
  ["John Travolta","John Travolta","Real Person / Celebrity"],
  ["John Wick","Keanu Reeves","John Wick"],
  ["Johnny Blaze / Ghost Rider","Nicolas Cage","Ghost Rider"],
  ["Jon Snow","Kit Harington","Game of Thrones"],
  ["Jonathan Crane","Cillian Murphy","Batman Begins"],
  ["Jonathan Pine","Tom Hiddleston","The Night Manager"],
  ["Jordan Belfort","Leonardo DiCaprio","The Wolf of Wall Street"],
  ["Joseph Cooper","Matthew McConaughey","Interstellar"],
  ["Josh Lyman","Bradley Whitford","The West Wing"],
  ["Juan Trippe","Alec Baldwin","The Aviator"],
  ["Jude Law","Jude Law","Real Person / Celebrity"],
  ["Judge Joseph Dredd","Sylvester Stallone","Judge Dredd"],
  ["Jules Winnfield","Samuel L. Jackson","Pulp Fiction"],
  ["Julia Roberts","Julia Roberts","Real Person / Celebrity"],
  ["Kanye West","Kanye West","Real Person / Celebrity"],
  ["Kate Beckett","Stana Katic","Castle"],
  ["Kenny McCormick","Matt Stone","South Park"],
  ["Kevin Chen Ka-kui","Jackie Chan","Police Story"],
  ["Kevin Costner","Kevin Costner","Real Person / Celebrity"],
  ["Kevin Hart","Kevin Hart","Real Person / Celebrity"],
  ["Kirk Lazarus","Robert Downey Jr.","Tropic Thunder"],
  ["Kobe Bryant","Kobe Bryant","Lakers court"],
  ["Komaram Bheem","N. T. Rama Rao Jr.","RRR"],
  ["Kyle Broflovski","Matt Stone","South Park"],
  ["Kylian Mbappé","Kylian Mbappé","Real Person / Celebrity"],
  ["Kylo Ren","Adam Driver","Star Wars"],
  ["Lamont Cranston","Alec Baldwin","The Shadow"],
  ["Larry David","Larry David","Curb Your Enthusiasm"],
  ["Lau Kin-ming","Andy Lau","Infernal Affairs"],
  ["Laurence Fishburne","Laurence Fishburne","Real Person / Celebrity"],
  ["Leonard Hofstadter","Johnny Galecki","The Big Bang Theory"],
  ["Leonardo DiCaprio","Leonardo DiCaprio","Real Person / Celebrity"],
  ["Lex Luthor","Kevin Spacey","Superman Returns"],
  ["Linus Caldwell","Matt Damon","Ocean's Eleven"],
  ["Liz Lemon","Tina Fey","30 Rock"],
  ["Lloyd Christmas","Jim Carrey","Dumb and Dumber"],
  ["Loki","Tom Hiddleston","Marvel's Avengers"],
  ["Lou Bloom","Jake Gyllenhaal","Nightcrawler"],
  ["Lt. Aldo Raine","Brad Pitt","Inglourious Basterds"],
  ["Lt. Col. Jimmy Doolittle","Alec Baldwin","Pearl Harbor"],
  ["Lt. Colonel John Sheppard","Joe Flanigan","Stargate Atlantis"],
  ["Lt. Daniel Kaffee","Tom Cruise","A Few Good Men"],
  ["Lucifer Morningstar","Tom Ellis","Lucifer"],
  ["Luke Cage","Mike Colter","Luke Cage"],
  ["Luke Hobbs","Dwayne Johnson","Fast & Furious"],
  ["Mace Windu","Samuel L. Jackson","Star Wars"],
  ["Madeline Martha Mackenzie","Reese Witherspoon","Big Little Lies"],
  ["Mads Mikkelsen","Mads Mikkelsen","Real Person / Celebrity"],
  ["Major Marquis Warren","Samuel L. Jackson","The Hateful Eight"],
  ["Malcolm Crowe","Bruce Willis","The Sixth Sense"],
  ["Malcolm Reynolds","Nathan Fillion","Firefly"],
  ["Malcolm X","Denzel Washington","Malcolm X"],
  ["Maleficent","Angelina Jolie","Maleficent"],
  ["Mark Watney","Matt Damon","The Martian"],
  ["Martin Riggs","Mel Gibson","Lethal Weapon"],
  ["Martin Sheen","Martin Sheen","Real Person / Celebrity"],
  ["Marty McFly","Michael J. Fox","Back to the Future"],
  ["Mathayus","Dwayne Johnson","The Scorpion King"],
  ["Matt Damon","Matt Damon","Real Person / Celebrity"],
  ["Matt Murdock","Ben Affleck","Daredevil"],
  ["Matthew McConaughey","Matthew McConaughey","Real Person / Celebrity"],
  ["Maverick / Pete Mitchell","Tom Cruise","Top Gun"],
  ["Max Black","Kat Dennings","2 Broke Girls"],
  ["Max Rockatansky","Mel Gibson","Mad Max"],
  ["Max Rockatansky","Tom Hardy","Mad Max: Fury Road"],
  ["Maximus Decimus Meridius","Russell Crowe","Gladiator"],
  ["Melinda Gordon","Jennifer Love Hewitt","Ghost Whisperer"],
  ["Meryl Streep","Meryl Streep","Real Person / Celebrity"],
  ["Mia Thermopolis","Anne Hathaway","The Princess Diaries"],
  ["Michael B. Jordan","Michael B. Jordan","Real Person / Celebrity"],
  ["Michael Clayton","George Clooney","Michael Clayton"],
  ["Michael Corleone","Al Pacino","The Godfather"],
  ["Michael Douglas","Michael Douglas","Real Person / Celebrity"],
  ["Michael Fassbender","Michael Fassbender","Real Person / Celebrity"],
  ["Michael Kelso","Ashton Kutcher","That '70s Show"],
  ["Michael Scofield","Wentworth Miller","Prison Break"],
  ["Michael Scott","Steve Carell","The Office"],
  ["Michonne","Danai Gurira","The Walking Dead"],
  ["Miranda Priestly","Meryl Streep","The Devil Wears Prada"],
  ["Morgan Freeman","Morgan Freeman","Real Person / Celebrity"],
  ["Morpheus","Laurence Fishburne","The Matrix"],
  ["Morty Smith","Justin Roiland","Rick and Morty"],
  ["Mr. Bean","Rowan Atkinson","Mr. Bean"],
  ["Natalie Cook","Cameron Diaz","Charlie's Angels"],
  ["Natalie Portman","Natalie Portman","Real Person / Celebrity"],
  ["Natasha Romanoff","Scarlett Johansson","The Avengers"],
  ["Navin R. Johnson","Steve Martin","The Jerk"],
  ["Negan","Jeffrey Dean Morgan","The Walking Dead"],
  ["Neil deGrasse Tyson","Neil deGrasse Tyson","Real Person / Celebrity"],
  ["Neil McCauley","Robert De Niro","Heat"],
  ["Neo","Keanu Reeves","The Matrix"],
  ["Neytiri","Zoe Saldana","Avatar"],
  ["Nicholas Brody","Damian Lewis","Homeland"],
  ["Nick Fury","Samuel L. Jackson","Marvel's Avengers"],
  ["Nicolas Cage","Nicolas Cage","Real Person / Celebrity"],
  ["Noah Calhoun","Ryan Gosling","The Notebook"],
  ["Norman Osborn","Willem Dafoe","Spider-Man"],
  ["Norman Reedus","Norman Reedus","Real Person / Celebrity"],
  ["Novak Djokovic","Novak Djokovic","Real Person / Celebrity"],
  ["Odin","Anthony Hopkins","Thor"],
  ["Oscar Isaac","Oscar Isaac","Real Person / Celebrity"],
  ["Owen Grady","Chris Pratt","Jurassic World"],
  ["Owen Wilson","Owen Wilson","Real Person / Celebrity"],
  ["Pam Beesly","Jenna Fischer","The Office"],
  ["Patrick Bateman","Christian Bale","American Psycho"],
  ["Patrick Jane","Simon Baker","The Mentalist"],
  ["Paul Atreides","Timothée Chalamet","Dune"],
  ["Paul Rudd","Paul Rudd","Real Person / Celebrity"],
  ["Peacemaker","John Cena","Peacemaker"],
  ["Penny","Kaley Cuoco","The Big Bang Theory"],
  ["Pennywise","Bill Skarsgård","IT"],
  ["Pete Maverick Mitchell","Tom Cruise","Top Gun"],
  ["Peter Parker","Andrew Garfield","The Amazing Spider-Man"],
  ["Phil Wenneck","Bradley Cooper","The Hangover"],
  ["Phoebe Buffay","Lisa Kudrow","Friends"],
  ["President Josiah \"Jed\" Bartlet","Martin Sheen","The West Wing"],
  ["Prince Akeem","Eddie Murphy","Coming to America"],
  ["Professor Charles Xavier","Patrick Stewart","X-Men"],
  ["Qui-Gon Jinn","Liam Neeson","Star Wars"],
  ["Rachel Green","Jennifer Aniston","Friends"],
  ["Rafael Nadal","Rafael Nadal","Real Person / Celebrity"],
  ["Ragnar Lothbrok","Travis Fimmel","Vikings"],
  ["Raj Koothrappali","Kunal Nayyar","The Big Bang Theory"],
  ["Randy Marsh","Trey Parker","South Park"],
  ["Ransom Drysdale","Chris Evans","Knives Out"],
  ["Ray","Colin Farrell","In Bruges"],
  ["Raymond Reddington","James Spader","The Blacklist"],
  ["Richard B. Riddick","Vin Diesel","The Chronicles of Riddick"],
  ["Richard Castle","Nathan Fillion","Castle"],
  ["Richard Gere","Richard Gere","Real Person / Celebrity"],
  ["Richard Kimble","Harrison Ford","The Fugitive"],
  ["Rick Deckard","Harrison Ford","Blade Runner"],
  ["Rick Grimes","Andrew Lincoln","The Walking Dead"],
  ["Rick Sanchez","Justin Roiland","Rick and Morty"],
  ["Ricky Bobby","Will Ferrell","Talladega Nights"],
  ["Rob Lowe","Rob Lowe","Real Person / Celebrity"],
  ["Robert De Niro","Robert De Niro","Real Person / Celebrity"],
  ["Robert McCall","Denzel Washington","The Equalizer"],
  ["Robert Pattinson","Robert Pattinson","Real Person / Celebrity"],
  ["Robin Williams","Robin Williams","Real Person / Celebrity"],
  ["RoboCop","Peter Weller","RoboCop"],
  ["Rocky Balboa","Sylvester Stallone","Rocky"],
  ["Ron Burgundy","Will Ferrell","Anchorman"],
  ["Ron Weasley","Rupert Grint","Harry Potter"],
  ["Ross Geller","David Schwimmer","Friends"],
  ["Rubeus Hagrid","Robbie Coltrane","Harry Potter"],
  ["Rust Cohle","Matthew McConaughey","True Detective"],
  ["Rusty Ryan","Brad Pitt","Ocean's Eleven"],
  ["Ryan Gosling","Ryan Gosling","Real Person / Celebrity"],
  ["Ryan Reynolds","Ryan Reynolds","Real Person / Celebrity"],
  ["Sam Ace Rothstein","Robert De Niro","Casino"],
  ["Sam Seaborn","Rob Lowe","The West Wing"],
  ["Sam Winchester","Jared Padalecki","Supernatural"],
  ["Samuel L. Jackson","Samuel L. Jackson","Real Person / Celebrity"],
  ["Sandra Bullock","Sandra Bullock","Real Person / Celebrity"],
  ["Saul Berenson","Mandy Patinkin","Homeland"],
  ["Saul Goodman","Bob Odenkirk","Breaking Bad"],
  ["Scarlet Witch","Elizabeth Olsen","Marvel's Avengers"],
  ["Scott Lang / Ant-Man","Paul Rudd","Marvel's Avengers"],
  ["Sean Archer","John Travolta","Face/Off"],
  ["Sean Dignam","Mark Wahlberg","The Departed"],
  ["Sebastian Wilder","Ryan Gosling","La La Land"],
  ["Seeley Booth","David Boreanaz","Bones"],
  ["Serena Williams","Serena Williams","Real Person / Celebrity"],
  ["Sergeant Terry Jeffords","Terry Crews","Brooklyn Nine-Nine"],
  ["Seth","Jonah Hill","Superbad"],
  ["Sheldon Cooper","Jim Parsons","The Big Bang Theory"],
  ["Sherlock Holmes","Benedict Cumberbatch","Sherlock (BBC)"],
  ["Sherlock Holmes","Robert Downey Jr.","Sherlock Holmes"],
  ["Simu Liu","Simu Liu","Real Person / Celebrity"],
  ["Snoop Dogg","Snoop Dogg","Real Person / Celebrity"],
  ["Sofia Vergara","Sofia Vergara","Real Person / Celebrity"],
  ["Special Agent Leroy Jethro Gibbs","Mark Harmon","NCIS"],
  ["Spike","James Marsters","Buffy the Vampire Slayer"],
  ["Spock","Leonard Nimoy","Star Trek: The Original Series"],
  ["Stan Marsh","Trey Parker","South Park"],
  ["Stanley Ipkiss as The Mask","Jim Carrey","The Mask"],
  ["Star-Lord","Chris Pratt","Marvel's Avengers"],
  ["Stephen Colbert","Stephen Colbert","Real Person / Celebrity"],
  ["Steve Rogers","Chris Evans","Marvel's Avengers"],
  ["Stringer Bell","Idris Elba","The Wire"],
  ["Summer Smith","Spencer Grammer","Rick and Morty"],
  ["Sylvester Stallone","Sylvester Stallone","Real Person / Celebrity"],
  ["Tallahassee","Woody Harrelson","Zombieland"],
  ["Taylor Swift","Taylor Swift","Real Person / Celebrity"],
  ["Ted Mosby","Josh Radnor","How I Met Your Mother"],
  ["Thanos","Josh Brolin","Marvel's Avengers"],
  ["The Eleventh Doctor","Matt Smith","Doctor Who"],
  ["The Narrator","Edward Norton","Fight Club"],
  ["The Tenth Doctor","David Tennant","Doctor Who"],
  ["The Terminator T-800","Arnold Schwarzenegger","The Terminator"],
  ["The Twelfth Doctor","Peter Capaldi","Doctor Who"],
  ["Thor","Chris Hemsworth","Marvel's Avengers"],
  ["Tim \"The Tool Man\" Taylor","Tim Allen","Home Improvement"],
  ["Tim Allen","Tim Allen","Real Person / Celebrity"],
  ["Tom Cruise","Tom Cruise","Real Person / Celebrity"],
  ["Tom Hanks","Tom Hanks","Real Person / Celebrity"],
  ["Tom Hardy","Tom Hardy","Real Person / Celebrity"],
  ["Tom Hiddleston","Tom Hiddleston","Real Person / Celebrity"],
  ["Tom Selleck","Tom Selleck","Real Person / Celebrity"],
  ["Tommy Shelby","Cillian Murphy","Peaky Blinders"],
  ["Tony Leung Chiu-wai","Tony Leung Chiu-wai","Real Person / Celebrity"],
  ["Tony Montana","Al Pacino","Scarface"],
  ["Tony Soprano","James Gandolfini","The Sopranos"],
  ["Tony Stark","Robert Downey Jr.","Marvel's Avengers"],
  ["Travis Bickle","Robert De Niro","Taxi Driver"],
  ["Tyler Durden","Brad Pitt","Fight Club"],
  ["Tyler Rake","Chris Hemsworth","Extraction"],
  ["Tyrion Lannister","Peter Dinklage","Game of Thrones"],
  ["Venus Williams","Venus Williams","Real Person / Celebrity"],
  ["Vince Vaughn","Vince Vaughn","Real Person / Celebrity"],
  ["Vincent Hanna","Al Pacino","Heat"],
  ["Vincent Vega","John Travolta","Pulp Fiction"],
  ["Vivian Ward","Julia Roberts","Pretty Woman"],
  ["Walter White","Bryan Cranston","Breaking Bad"],
  ["Wednesday Addams","Jenna Ortega","Wednesday"],
  ["Will Ferrell","Will Ferrell","Real Person / Celebrity"],
  ["Will Hunting","Matt Damon","Good Will Hunting"],
  ["Will Smith","Will Smith","The Fresh Prince of Bel-Air"],
  ["Willem Dafoe","Willem Dafoe","Real Person / Celebrity"],
  ["William Munny","Clint Eastwood","Unforgiven"],
  ["William Riker","Jonathan Frakes","Star Trek: The Next Generation"],
  ["William Somerset","Morgan Freeman","Se7en"],
  ["Willow Rosenberg","Alyson Hannigan","Buffy the Vampire Slayer"],
  ["Willy Wonka","Johnny Depp","Charlie and the Chocolate Factory"],
  ["Wolverine","Hugh Jackman","Marvel's Avengers / X-Men"],
  ["Woody Harrelson","Woody Harrelson","Real Person / Celebrity"],
  ["Worf","Michael Dorn","Star Trek: The Next Generation"],
  ["Xu Wenwu","Tony Leung Chiu-wai","Shang-Chi and the Legend of the Ten Rings"],
  ["Ziva David","Cote de Pablo","NCIS"],
] as const;
