use super::*;
#[test]
fn rust_never_emits_a_null_the_frontend_schema_refuses() {
    // The cross-layer direction that went unchecked for nine rounds: Rust
    // WRITING something zod cannot read. Browser mode never touches Rust,
    // so nothing else catches it.
    for (name, config) in [
        ("created", created_fixture()),
        ("complete", fixture()),
        ("scene", scene_fixture()),
    ] {
        let config = validate_and_normalize_config(config).unwrap();
        let found = forbidden_nulls(&config);
        assert!(
            found.is_empty(),
            "{name} fixture serialized nulls that zod's .optional() rejects: {found:?}"
        );
    }

    // Positively: a freshly created draft job carries no clip, and the key
    // must be missing rather than null. `createDraftGenerationJob` never
    // sets clipId, so this is every project that has ever been created.
    let created = validate_and_normalize_config(created_fixture()).unwrap();
    let json = serde_json::to_string_pretty(&created).unwrap();
    let value: serde_json::Value = serde_json::from_str(&json).unwrap();
    let job = object_of(&value["generationJobs"][0], "generationJobs[0]");
    assert!(
        !job.contains_key("clipId"),
        "clipId must be absent, not null: {job:?}"
    );
    assert!(!json.contains("\"clipId\""), "clipId leaked into {json}");
}

// Writes the REAL serialised output of `validate_and_normalize_config`
// into `fixtures/rust-serialized-*.json`, which the frontend test suite
// parses with its own zod schema. This is how the two-validator contract
// stops being hand-maintained: a field added to Rust as an `Option`
// without `skip_serializing_if` (or added to zod as a bare `.optional()`)
// changes these bytes and fails on the frontend side, with nobody having
// to remember to extend `NON_NULLABLE_OPTIONAL_KEYS`.
//
// THESE FILES ARE GENERATED BY `cargo test` AND COMMITTED ON PURPOSE. If
// `git status` is dirty after a test run, the wire format changed: re-run
// the frontend schema tests against the new bytes before committing them.
//
// The output is deterministic — every input is a checked-in fixture or is
// derived from one. The imported-reference case runs the real product code
// path inside a `tempfile::tempdir()`, but the temp path cannot leak into
// the JSON because references store project-relative paths only
// (`references/<file>`); the assertion below proves it per run.
#[test]
fn serialized_wire_format_matches_frontend_fixtures() {
    fn serialize(config: &ProjectConfig) -> String {
        let mut json = serde_json::to_string_pretty(config).unwrap();
        // Trailing newline so the committed bytes are stable under editors
        // and `git diff` alike.
        json.push('\n');
        json
    }

    fn write_fixture(name: &str, json: &str) {
        let path = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../fixtures")
            .join(name);
        if std::env::var_os("SLOPUS_UPDATE_FIXTURES").is_some() {
            fs::write(&path, json).unwrap();
        } else {
            let expected = fs::read_to_string(&path).unwrap().replace("\r\n", "\n");
            assert_eq!(json, expected, "{} changed; run with SLOPUS_UPDATE_FIXTURES=1 to update intentionally", path.display());
        }
    }

    write_fixture(
        "rust-serialized-created.json",
        &serialize(&validate_and_normalize_config(created_fixture()).unwrap()),
    );
    write_fixture(
        "rust-serialized-complete.json",
        &serialize(&validate_and_normalize_config(fixture()).unwrap()),
    );
    // The external-location shapes: an absolute Windows path, an absolute
    // POSIX one, a UNC share, and a copied image beside them. Rust writes
    // exactly these bytes; the frontend suite parses them with real zod.
    write_fixture(
        "rust-serialized-external-media.json",
        &serialize(&validate_and_normalize_config(external_fixture()).unwrap()),
    );
    // Everything a scene added: shots with start times and per-shot
    // settings, a scene length, and the two sound fields.
    write_fixture(
        "rust-serialized-scene.json",
        &serialize(&validate_and_normalize_config(scene_fixture()).unwrap()),
    );

    // An ACTUALLY IMPORTED reference: produced by the same function the
    // create-project command calls, not a hand-written fixture record.
    let root = tempfile::tempdir().unwrap();
    let source = root.path().join("harbor facade.png");
    fs::write(&source, b"\x89PNG\r\n\x1a\n").unwrap();
    let imported = create_project_in_with_references(
        root.path(),
        &created_fixture(),
        std::slice::from_ref(&source),
    )
    .unwrap();
    assert_eq!(
        imported.config.references[0].relative_path.as_deref(),
        Some("references/harbor facade.png"),
        "the imported reference must be stored as a project-relative path"
    );
    let json = serialize(&imported.config);
    // The randomly named temp directory is the only non-deterministic input
    // in this test; if any part of it reached the JSON the committed file
    // would change on every run and dirty the tree at random.
    let temp_marker = root
        .path()
        .file_name()
        .unwrap()
        .to_string_lossy()
        .into_owned();
    assert!(
        !json.contains(&temp_marker),
        "the temp directory name '{temp_marker}' leaked into the generated fixture: {json}"
    );
    write_fixture("rust-serialized-initial-reference.json", &json);
}

#[test]
fn is_iso_datetime_agrees_with_real_zod_on_every_recorded_case() {
    // fixtures/iso-datetime-cases.json is a differential harness: 932
    // strings (single-character mutations, insertions, deletions and
    // truncations of valid stamps, plus calendar and time boundaries),
    // each labelled with the verdict of the frontend's real
    // `z.string().datetime()` from the installed zod 3.25.76. The
    // hand-written table above documents intent readably; THIS test is the
    // one that proves parity, and it is committed rather than run once as
    // a throwaway so a regression is caught by `cargo test`.
    let cases: Vec<(String, bool)> =
        serde_json::from_str(include_str!("../../../fixtures/iso-datetime-cases.json"))
            .expect("fixtures/iso-datetime-cases.json is not a [string, bool] array");
    assert!(
        cases.len() > 900,
        "the harness lost cases: only {} remain",
        cases.len()
    );

    // Collect every disagreement before failing: one assert per iteration
    // would report a single string and hide the shape of the regression.
    let mut disagreements = Vec::new();
    for (value, zod_accepts) in &cases {
        if is_iso_datetime(value) != *zod_accepts {
            disagreements.push(format!(
                "'{value}': zod {}, rust {}",
                if *zod_accepts { "accepts" } else { "rejects" },
                if *zod_accepts { "rejects" } else { "accepts" }
            ));
        }
    }
    assert!(
        disagreements.is_empty(),
        "{} of {} cases disagree with zod; first {}:\n{}",
        disagreements.len(),
        cases.len(),
        disagreements.len().min(10),
        disagreements
            .iter()
            .take(10)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}

#[test]
fn both_fixtures_round_trip_losslessly_through_json() {
    for (name, config) in [
        ("created", created_fixture()),
        ("complete", fixture()),
        ("scene", scene_fixture()),
    ] {
        let normalized =
            without_derived_project_state(validate_and_normalize_config(config).unwrap());
        let json = serde_json::to_string_pretty(&normalized).unwrap();
        let reparsed: ProjectConfig = serde_json::from_str(&json).unwrap();
        assert_eq!(
            reparsed, normalized,
            "{name} fixture lost data in a round trip"
        );
        assert_eq!(
            validate_and_normalize_config(reparsed).unwrap(),
            normalized,
            "{name} fixture failed to re-validate after a round trip"
        );
    }
}

#[test]
fn absent_non_nullable_optionals_are_omitted_entirely() {
    let mut config = fixture();
    config.assets[0].duration_ms = None;
    config.assets[0].width = None;
    config.assets[0].height = None;
    config.timeline.tracks[0].clips[0].color = None;
    config.generation_jobs[0].clip_id = None;
    let config = without_derived_project_state(validate_and_normalize_config(config).unwrap());

    let found = forbidden_nulls(&config);
    assert!(found.is_empty(), "emitted forbidden nulls: {found:?}");

    let value = serde_json::to_value(&config).unwrap();
    let asset = object_of(&value["assets"][0], "assets[0]");
    for key in ["durationMs", "width", "height"] {
        assert!(!asset.contains_key(key), "assets[0].{key} must be omitted");
    }
    let clip = object_of(&value["timeline"]["tracks"][0]["clips"][0], "clips[0]");
    assert!(!clip.contains_key("color"), "clip color must be omitted");
    // The clip's OWN durationMs is required and must survive — the omission
    // is per field, not per key name.
    assert_eq!(clip["durationMs"], serde_json::json!(8000));
    let job = object_of(&value["generationJobs"][0], "generationJobs[0]");
    assert!(!job.contains_key("clipId"), "job clipId must be omitted");

    let reparsed: ProjectConfig = serde_json::from_value(value).unwrap();
    assert_eq!(
        reparsed, config,
        "omitted optionals did not come back as None"
    );
}

#[test]
fn nullable_optionals_still_serialize_as_explicit_null() {
    // The guard against "fixing" the clipId break by blanket-adding
    // skip_serializing_if: every field below is `.nullable()` on the
    // frontend, so an explicit null is what zod expects. Dropping the key
    // breaks the other direction just as badly.
    fn assert_explicit_null(parent: &serde_json::Value, path: &str, key: &str) {
        let fields = object_of(parent, path);
        assert!(
            fields.contains_key(key),
            "{path}.{key} is .nullable() on the frontend and must stay present"
        );
        assert!(
            fields[key].is_null(),
            "{path}.{key} must serialize as null when None, got {}",
            fields[key]
        );
    }

    let mut config = fixture();
    config.thumbnail = None;
    config.references[0].content = None;
    config.references[0].relative_path = None;
    config.generation_jobs[0].provider_id = None;
    config.generation_jobs[0].output_relative_path = None;
    config.generation_jobs[0].error = None;
    config
        .provider_settings
        .get_mut("minimax-h3")
        .unwrap()
        .model = None;
    let config = validate_and_normalize_config(config).unwrap();

    let json = serde_json::to_string_pretty(&config).unwrap();
    assert!(
        json.contains("\"thumbnail\": null"),
        "thumbnail must serialize as an explicit null: {json}"
    );
    let value: serde_json::Value = serde_json::from_str(&json).unwrap();
    assert_explicit_null(&value, "config", "thumbnail");
    assert_explicit_null(&value["references"][0], "references[0]", "content");
    assert_explicit_null(&value["references"][0], "references[0]", "relativePath");
    assert_explicit_null(
        &value["generationJobs"][0],
        "generationJobs[0]",
        "providerId",
    );
    assert_explicit_null(
        &value["generationJobs"][0],
        "generationJobs[0]",
        "outputRelativePath",
    );
    assert_explicit_null(&value["generationJobs"][0], "generationJobs[0]", "error");
    assert_explicit_null(
        &value["providerSettings"]["minimax-h3"],
        "providerSettings['minimax-h3']",
        "model",
    );
}

#[test]
fn iso_datetime_matches_the_frontend_datetime_rules() {
    for value in [
        "2026-01-01T00:00:00.000Z",
        "2026-01-01T00:00:00Z",
        "2026-01-01T00:00:00.123456789Z",
        "2024-02-29T23:59:59Z",
        "2000-02-29T00:00:00Z",
        "2026-12-31T23:59:59.9Z",
        // zod's seconds group is optional: `(:[0-5]\d(\.\d+)?)?`. Verified
        // against the installed zod 3.25.76, which accepts this. Rejecting
        // it would make a legitimate file unsavable in the desktop app.
        "2026-01-01T00:00Z",
        "2026-12-31T23:59Z",
    ] {
        assert!(is_iso_datetime(value), "rejected valid date-time '{value}'");
    }
    for value in [
        "2026-01-01",
        "2026-01-01T00:00:00",
        "2026-01-01T00:00:00+01:00",
        "2026-01-01t00:00:00z",
        "2026-01-01T00:00:00.Z",
        "",
        "not a date",
        "2026-01-01T00:00:00.000Z ",
        " 2026-01-01T00:00:00.000Z",
        "2026-01-01T00:00:00.000ZZ",
        "2026-13-01T00:00:00Z",
        "2026-00-01T00:00:00Z",
        "2026-02-30T00:00:00Z",
        "2026-01-00T00:00:00Z",
        "2025-02-29T00:00:00Z",
        "1900-02-29T00:00:00Z",
        "2026-01-01T24:00:00Z",
        "2026-01-01T00:60:00Z",
        "2026-01-01T00:00:60Z",
        "2026-01-01 00:00:00Z",
        "20260101T000000Z",
        // The fraction belongs to the seconds group, so it cannot follow
        // bare minutes.
        "2026-01-01T00:00.5Z",
        "2026-01-01T00:00",
        "2026-01-01T00:60Z",
        "2026-01-01T24:00Z",
        "2026-01-01T00:00:Z",
    ] {
        assert!(
            !is_iso_datetime(value),
            "accepted invalid date-time '{value}'"
        );
    }
}

#[test]
fn every_date_field_is_checked_the_way_the_frontend_checks_it() {
    // A date Rust accepts and zod refuses is written to disk and the project
    // disappears from the library on the next launch, so every date field
    // has to be covered — not just the two on the config root.
    assert!(validate_and_normalize_config(fixture()).is_ok());
    assert!(validate_and_normalize_config(created_fixture()).is_ok());

    fn rejects(field: &str, break_config: impl FnOnce(&mut ProjectConfig)) {
        let mut config = fixture();
        break_config(&mut config);
        let error = validate_and_normalize_config(config)
            .expect_err(&format!("accepted a {field} the frontend schema rejects"));
        assert!(
            error.contains("ISO date-time"),
            "unexpected error for {field}: {error}"
        );
    }

    rejects("project createdAt", |config| {
        config.created_at = "2026-01-01".into();
    });
    rejects("project updatedAt", |config| {
        config.updated_at = "2026-01-02T03:04:05".into();
    });
    rejects("asset createdAt", |config| {
        config.assets[0].created_at = "2026-01-01T00:10:00+01:00".into();
    });
    rejects("reference createdAt", |config| {
        config.references[0].created_at = "2026-01-01t00:05:00.000z".into();
    });
    rejects("job createdAt", |config| {
        config.generation_jobs[0].created_at = String::new();
    });
    rejects("job updatedAt", |config| {
        config.generation_jobs[0].updated_at = "not a date".into();
    });
    rejects("agent message createdAt", |config| {
        config.agent_conversation.messages[0].created_at = "2026-01-01T00:11:00".into();
    });
}

#[test]
fn legacy_project_defaults_to_video_and_persists_its_type() {
    let root = tempfile::tempdir().unwrap();
    let legacy = include_str!("../../../fixtures/project-v1-created.json");
    assert!(serde_json::from_str::<serde_json::Value>(legacy)
        .unwrap().get("generationType").is_none());
    fs::write(root.path().join(PROJECT_FILE_NAME), legacy).unwrap();
    let opened = read_project(root.path()).unwrap();
    assert_eq!(opened.config.generation_type, GenerationType::Video);
    write_project(root.path(), &opened.config).unwrap();
    let saved: serde_json::Value = serde_json::from_slice(
        &fs::read(root.path().join(PROJECT_FILE_NAME)).unwrap(),
    ).unwrap();
    assert_eq!(saved["generationType"], "video");
}

#[test]
fn generation_types_survive_create_save_and_reopen() {
    for generation_type in ["video", "image", "3d", "music", "speech"] {
        let root = tempfile::tempdir().unwrap();
        let mut value = serde_json::to_value(created_fixture()).unwrap();
        value["generationType"] = serde_json::json!(generation_type);
        let config: ProjectConfig = serde_json::from_value(value).unwrap();
        let created = create_project_in(root.path(), &config).unwrap();
        let folder = Path::new(&created.folder_path);
        let opened = read_project(folder).unwrap();
        write_project(folder, &opened.config).unwrap();
        let reopened = read_project(folder).unwrap();
        assert_eq!(reopened.config.generation_type, config.generation_type);
        assert_eq!(serde_json::to_value(reopened.config).unwrap()["generationType"], generation_type);
    }
}

#[test]
fn invalid_explicit_generation_types_are_rejected() {
    for generation_type in [
        serde_json::Value::Null, serde_json::json!(""), serde_json::json!("unknown"),
        serde_json::json!("Video"), serde_json::json!(3),
    ] {
        let mut value = serde_json::to_value(created_fixture()).unwrap();
        value["generationType"] = generation_type;
        assert!(serde_json::from_value::<ProjectConfig>(value).is_err());
    }
}

#[test]
fn complete_project_create_open_save_reopen_is_lossless() {
    let root = tempfile::tempdir().unwrap();
    let expected =
        without_derived_project_state(validate_and_normalize_config(fixture()).unwrap());
    let created = create_project_in(root.path(), &expected).unwrap();
    assert_eq!(created.config, expected);

    let project_folder = PathBuf::from(&created.folder_path);
    let opened = read_project(&project_folder).unwrap();
    assert_eq!(opened.config, expected);

    let mut saved = opened.config.clone();
    saved.updated_at = "2026-02-03T04:05:06.000Z".into();
    write_project(&project_folder, &saved).unwrap();
    assert_eq!(read_project(&project_folder).unwrap().config, saved);

    let mut directories = Vec::new();
    fn collect_directories(root: &Path, current: &Path, output: &mut Vec<String>) {
        for entry in fs::read_dir(current).unwrap() {
            let path = entry.unwrap().path();
            if path.is_dir() {
                output.push(
                    path.strip_prefix(root)
                        .unwrap()
                        .to_string_lossy()
                        .replace('\\', "/"),
                );
                collect_directories(root, &path, output);
            }
        }
    }
    collect_directories(&project_folder, &project_folder, &mut directories);
    directories.sort();
    assert_eq!(
        directories,
        [
            "cache",
            "exports",
            "media",
            "media/generated",
            "media/imported",
            "references",
            "thumbnails",
        ]
    );
    let files: Vec<_> = fs::read_dir(&project_folder)
        .unwrap()
        .filter_map(Result::ok)
        .filter(|entry| entry.path().is_file())
        .map(|entry| entry.file_name().to_string_lossy().into_owned())
        .collect();
    assert_eq!(files, [PROJECT_FILE_NAME]);
}

#[test]
fn chroma_key_survives_save_and_reopen_and_validates_settings() {
    let mut config = fixture();
    config.timeline.tracks[0].clips[0].chroma_key = Some(ClipChromaKey {
        color: "#12ABef".into(),
        tolerance: 27.0,
    });
    let config = without_derived_project_state(validate_and_normalize_config(config).unwrap());
    let root = tempfile::tempdir().unwrap();
    let created = create_project_in(root.path(), &config).unwrap();
    let folder = PathBuf::from(&created.folder_path);
    write_project(&folder, &config).unwrap();
    assert_eq!(read_project(&folder).unwrap().config, config);
    let json = serde_json::to_value(&config).unwrap();
    assert_eq!(json["timeline"]["tracks"][0]["clips"][0]["chromaKey"]["color"], "#12ABef");
    for (color, tolerance) in [("green", 20.0), ("#12345g", 20.0), ("#00ff00", -1.0), ("#00ff00", 101.0), ("#00ff00", f64::NAN)] {
        let mut invalid = config.clone();
        invalid.timeline.tracks[0].clips[0].chroma_key = Some(ClipChromaKey { color: color.into(), tolerance });
        assert!(validate_and_normalize_config(invalid).unwrap_err().contains("chroma key"));
    }
    let mut removed = config.clone();
    removed.timeline.tracks[0].clips[0].chroma_key = None;
    write_project(&folder, &removed).unwrap();
    assert!(read_project(&folder).unwrap().config.timeline.tracks[0].clips[0].chroma_key.is_none());
}

#[test]
fn deleting_a_project_removes_its_folder_and_every_file_inside_it() {
    let parent = tempfile::tempdir().unwrap();
    let project = project_folder_at(&parent.path().join("Disposable project"));
    fs::create_dir_all(project.join("media/generated")).unwrap();
    fs::write(project.join("media/generated/scene.mp4"), b"video").unwrap();
    let id = read_project(&project).unwrap().config.id;

    delete_project_folder(&project.to_string_lossy(), &id).unwrap();

    assert!(!project.exists());
    assert!(parent.path().is_dir());
}

#[test]
fn deletion_refuses_a_different_project_identity_and_keeps_the_folder() {
    let parent = tempfile::tempdir().unwrap();
    let project = project_folder_at(&parent.path().join("Keep this project"));

    let error =
        delete_project_folder(&project.to_string_lossy(), "some-other-project").unwrap_err();

    assert!(error.contains("not the project selected for deletion"));
    assert!(project.is_dir());
    assert!(project.join(PROJECT_FILE_NAME).is_file());
}

#[test]
fn old_v1_documents_receive_empty_persistence_containers() {
    let mut value = serde_json::to_value(fixture()).unwrap();
    let object = value.as_object_mut().unwrap();
    object.remove("references");
    object.remove("generationJobs");
    object.remove("agentConversation");
    object.remove("providerSettings");
    let config: ProjectConfig = serde_json::from_value(value).unwrap();
    assert!(config.references.is_empty());
    assert!(config.generation_jobs.is_empty());
    assert!(config.agent_conversation.messages.is_empty());
    assert!(config.provider_settings.is_empty());
}

